In [58]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [96]:
n = 3
A = np.random.rand(n,n)
A_inv = np.linalg.inv(A)

u = np.random.rand(n,1)
v = np.random.rand(n,1)

print(A)
print()

print(A_inv)
print()
print(u*v.T)
# print(np.outer(u,v)) # to to samo co z mnozeniem
print()
# print(np.add(A, u*v.T))
print(A + u*v.T)
print()
print(np.linalg.inv(A + u*v.T))


[[0.10336816 0.47787623 0.87665138]
 [0.23243811 0.89702031 0.23468542]
 [0.73551252 0.44119375 0.86090602]]

[[-1.54613804  0.05695557  1.55888956]
 [ 0.06356798  1.28507443 -0.41504552]
 [ 1.28836142 -0.70722974  0.04243517]]

[[0.44652594 0.12147119 0.33777739]
 [0.35488616 0.09654186 0.26845589]
 [0.02592149 0.00705158 0.01960848]]

[[0.54989409 0.59934743 1.21442876]
 [0.58732427 0.99356217 0.50314132]
 [0.76143402 0.44824533 0.88051449]]

[[-2.01451485 -0.0515885   2.80795046]
 [ 0.41585784  1.36671591 -1.35452735]
 [ 1.53037094 -0.65114519 -0.60295253]]


In [111]:
def sherman_morrison(A, u, v):
    A_inv = np.linalg.inv(A)
    upp = A_inv * u * v.T * A_inv
    down = 1.0 + v.T * A_inv * u
    
    print(upp)
    print()
    print(down)
 
    print(upp/down)
#     return A_inv - upp/down

In [112]:
sherman_morrison(A, u, v)

[[1.06743939e+00 3.94044892e-04 8.20845211e-01]
 [1.43405516e-03 1.59430802e-01 4.62449604e-02]
 [4.30264419e-02 3.52701769e-03 3.53098452e-05]]

[[0.30960926 1.00691846 1.52655764]
 [1.0225594  1.12406348 0.88857858]
 [1.03339625 0.99501291 1.00083209]]
[[3.44769852e+00 3.91337439e-04 5.37709935e-01]
 [1.40241747e-03 1.41834341e-01 5.20437486e-02]
 [4.16359570e-02 3.54469540e-03 3.52804887e-05]]
