# <center> Zestaw 7
## <center> Ryszard Pręcikowski
### <center> 401433

In [4]:
import matplotlib.pyplot as plt
import numpy as np
import numpy.linalg as npl
from sympy import *
from sympy.abc import x
from sympy.calculus.util import continuous_domain
from typing import List
from decimal import Decimal
from pprint import  pprint

In [5]:
def plot_function(g_i, show = True, a=0, b=3, y_lim=None):
    gl = lambdify(x, g_i)
    x_v = np.linspace(a, b, 500)
    inter = continuous_domain(g_i, x, S.Reals)
    not_in = S.Reals - inter

    if type(not_in) is FiniteSet:
        p = plt.plot([], [], label = g_i)
        for idk in not_in:
            n_x = x_v[x_v < idk]
            x_v = x_v[x_v > idk]

            plt.plot(n_x, gl(n_x), c=p[0].get_c())
        plt.plot(x_v, gl(x_v), c=p[0].get_c())
    else:
        x_v = np.array([x_i for x_i in x_v if x_i in inter])
        plt.plot(x_v, gl(x_v),label = g_i)

    plt.ylim(y_lim)
    plt.legend()
    plt.grid(True)
    plt.xlabel("x")
    plt.ylabel('y')
    if show:
        plt.show()

def my_det_3x3(arr: List[List[Decimal]]):
    res = Decimal(0)
    for i in range(3):
        res += arr[0][(0-i) % 3] * arr[1][(1-i) % 3] * arr[2][(2-i) % 3]
        res -= arr[2][(0+i) % 3] * arr[1][(1+i) % 3] * arr[0][(2+i) % 3]
    return res

In [6]:
from decimal import Decimal
A = np.array([i/10 for i in range(1, 10)]).reshape(3, 3)

print(A)
print(npl.det(A)) #TAK NA SERIO TO DET = 0 !!!!!!!!!!!!

A_exact = [[Decimal(1 + i + (j*3)) / 10 for i in range(3)] for j in range(3)]
my_det_3x3(A_exact)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
6.661338147750926e-18


Decimal('0.000')

In [7]:
A_inv = npl.inv(A)
print(A_inv)
print(npl.cond(A))



[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
2.1118968335779856e+16


In [47]:
from sympy import *
eps = Symbol('{\\epsilon}')
M = Matrix([[1, 1+eps],
            [1-eps, 1]])

M

Matrix([
[             1, {\epsilon} + 1],
[1 - {\epsilon},              1]])

In [48]:
print(M.det())
m_det = M.det()


{\epsilon}**2


In [40]:
a = 1.0

while 1.0 + a > 1.0:
    a /= 4.0
print(a*4)

l, u, _ = M.LUdecomposition()

2.220446049250313e-16


In [41]:
l

Matrix([
[             1, 0],
[1 - {\epsilon}, 1]])

In [46]:
u.simplify()
u

Matrix([
[1, {\epsilon} + 1],
[0,  {\epsilon}**2]])

In [49]:
u.det()


{\epsilon}**2

tak samo